"""add url 

Revision ID: 3f1a8fb48004
Revises: fdaaf2cff4bc
Create Date: 2019-03-18 15:43:23.827978

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f1a8fb48004'
down_revision = 'fdaaf2cff4bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_url', sa.String(length=100), nullable=True))
    op.drop_column('user', 'image_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('image_url', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('user', 'avatar_url')
    # ### end Alembic commands ###
