"""add

Revision ID: 704b205de17c
Revises: 9f0a02777635
Create Date: 2019-03-20 23:48:46.067179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704b205de17c'
down_revision = '9f0a02777635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news', sa.Column('clicks', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'clicks')
    # ### end Alembic commands ###
