"""add

Revision ID: 95fa038a3b2e
Revises: a88e8c4d176d
Create Date: 2019-03-21 10:36:12.051203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95fa038a3b2e'
down_revision = 'a88e8c4d176d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('like_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'like_count')
    # ### end Alembic commands ###
