"""add gender

Revision ID: fdaaf2cff4bc
Revises: d00680ae0042
Create Date: 2019-03-18 10:23:42.498440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdaaf2cff4bc'
down_revision = 'd00680ae0042'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('gender', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('signature', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'signature')
    op.drop_column('user', 'gender')
    # ### end Alembic commands ###
